import React from 'react';
import { ShieldAlert, AlertTriangle, Info } from 'lucide-react';
import { NormalizedRiskAssessment } from '../../types/telemetry';
import { RISK_LEVEL_CONFIG } from '../../utils/constants';

interface RecommendedActionProps {
  risk: NormalizedRiskAssessment;
}

export const RecommendedAction: React.FC<RecommendedActionProps> = ({ risk }) => {
  const isCritical = risk.level === 'CRITICAL';
  const isHigh = risk.level === 'HIGH';
  const isDegraded = risk.status === 'DEGRADED';
  const config = RISK_LEVEL_CONFIG[risk.level] || RISK_LEVEL_CONFIG.LOW;

  return (
    <div
      className="cmd-panel"
      style={{
        border: `1px solid ${isDegraded ? '#f59e0b' : isCritical ? '#ef4444' : isHigh ? '#f97316' : 'var(--border-medium)'}`,
        background: isCritical
          ? 'linear-gradient(135deg, rgba(239, 68, 68, 0.15) 0%, rgba(15, 23, 42, 0.95) 100%)'
          : isHigh
          ? 'linear-gradient(135deg, rgba(249, 115, 22, 0.12) 0%, rgba(15, 23, 42, 0.95) 100%)'
          : 'var(--bg-panel)',
      }}
    >
      <div className="cmd-panel-header" style={{
        background: isCritical ? 'rgba(239, 68, 68, 0.2)' : isHigh ? 'rgba(249, 115, 22, 0.15)' : 'rgba(255, 255, 255, 0.02)',
      }}>
        <div className="cmd-panel-title" style={{
          color: isCritical ? '#f87171' : isHigh ? '#fb923c' : 'var(--text-secondary)',
        }}>
          {isCritical ? <ShieldAlert size={18} /> : <Info size={16} />}
          <span>Prescriptive Operational Mitigation</span>
        </div>
        <span
          className="badge"
          style={{
            background: 'rgba(56, 189, 248, 0.15)',
            color: '#38bdf8',
            border: '1px solid rgba(56, 189, 248, 0.35)',
            fontSize: '0.68rem',
            fontWeight: 700,
          }}
        >
          AI-GENERATED PROTOTYPE RECOMMENDATION
        </span>
      </div>

      <div className="cmd-panel-body" style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {/* Prominent Action Callout */}
        <div
          style={{
            padding: '14px 16px',
            background: 'var(--bg-panel-elevated)',
            borderLeft: `4px solid ${isDegraded ? '#f59e0b' : config.color}`,
            borderRadius: '0 var(--radius-sm) var(--radius-sm) 0',
            display: 'flex',
            alignItems: 'flex-start',
            gap: '12px',
          }}
        >
          <div style={{ color: isDegraded ? '#f59e0b' : config.color, marginTop: '2px' }}>
            {isCritical || isHigh ? <AlertTriangle size={22} /> : <Info size={20} />}
          </div>
          <div style={{ flex: 1 }}>
            <div style={{
              fontSize: '1rem',
              fontWeight: 700,
              color: isCritical ? '#fecaca' : 'var(--text-primary)',
              lineHeight: 1.4,
            }}>
              "{risk.recommended_action}"
            </div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
              Standard operating procedure corresponding to {risk.level} threat state (Score: {risk.score.toFixed(1)}/100).
            </div>
          </div>
        </div>

        {/* Prototype Safety Notice */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: '8px 12px',
          background: 'rgba(245, 158, 11, 0.08)',
          border: '1px solid rgba(245, 158, 11, 0.25)',
          borderRadius: 'var(--radius-sm)',
          fontSize: '0.72rem',
          color: '#fbbf24',
        }}>
          <AlertTriangle size={14} style={{ flexShrink: 0 }} />
          <span>
            <strong>Safety Notice:</strong> Automated prototype advisory generated by multi-criteria geotechnical engine. Site shift supervisors must confirm before executing evacuation or blasting holds.
          </span>
        </div>
      </div>
    </div>
  );
};
